version: 1.0.1

plugins:
  - jekyll-paginate

# Dependencies
highlighter:  rouge
markdown:	  kramdown

# Permalinks
permalink:        pretty

# Setup
baseurl:          "https://www.szylhabel.pl"

paginate:         5

exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "Gemfile",
  "Gemfile.lock",
  "package-lock.json",
  ".travis.yml",
  "README.md"]
